#!/usr/bin/env python3
"""
Dirichlet Feature Pipeline: Extractor Service.
Maps ClickHouse catalog column metadata to verified 200-feature security descriptors
with strict priority tier assignments, emitting payloads/features.json.

"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

# Ensure local service imports work regardless of working directory
current_dir = Path(__file__).resolve().parent
if str(current_dir) not in sys.path:
    sys.path.insert(0, str(current_dir))

from catalog_sync import CANONICAL_FEATURES_200, sync_catalog

# Exhaustive dictionary of all 200 verified canonical security features
KNOWN_FEATURES: Dict[str, Dict[str, Any]] = {
    col["name"]: {
        "priority": col["priority"],
        "data_type": col["type"],
        "domain": col["domain"],
        "is_core": col["priority"] >= 200,
    }
    for col in CANONICAL_FEATURES_200
}


def resolve_feature_cardinality(raw_columns: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Resolve column metadata into runtime feature definitions.

    Known canonical signals (200 features) receive verified priorities (100..255).
    Unknown shard columns (80 duplicated columns) receive priority = 0 (Untrusted Shadow Column).
    """
    features: List[Dict[str, Any]] = []

    for feature_id, col in enumerate(raw_columns, start=1):
        name = col["name"]
        data_type = col.get("type", "String")
        domain = col.get("domain", "unknown")

        if name in KNOWN_FEATURES:
            meta = KNOWN_FEATURES[name]
            features.append({
                "id": feature_id,
                "name": name,
                "data_type": data_type,
                "domain": meta["domain"],
                "priority": meta["priority"],
                "is_shadow": False,
            })
        else:
            # Untrusted Shadow Column generated by unqualified shard reflection
            features.append({
                "id": feature_id,
                "name": name,
                "data_type": data_type,
                "domain": domain,
                "priority": 0,
                "is_shadow": True,
            })

    return features


def extract_and_emit(
    simulate_duplication: bool = False,
    output_path: Path | None = None,
    live_db: bool = False,
    clickhouse_url: str = "http://localhost:8123",
) -> List[Dict[str, Any]]:
    """
    Synchronize catalog metadata, resolve feature priorities, and write payloads/features.json.
    """
    if output_path is None:
        repo_root = current_dir.parent.parent
        output_path = repo_root / "payloads" / "features.json"

    raw_columns = sync_catalog(
        simulate_duplication=simulate_duplication,
        live_db=live_db,
        clickhouse_url=clickhouse_url,
    )
    features = resolve_feature_cardinality(raw_columns)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(features, f, indent=2)

    return features


def main() -> None:
    parser = argparse.ArgumentParser(description="Dirichlet Feature Pipeline Extractor")
    parser.add_argument(
        "--simulate-duplication",
        action="store_true",
        help="Simulate multi-shard reflection defect emitting 280 features",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Emit canonical 200 features",
    )
    parser.add_argument(
        "--live-clickhouse",
        action="store_true",
        help="Query live ClickHouse instance via HTTP instead of offline catalog",
    )
    parser.add_argument(
        "--clickhouse-url",
        default="http://localhost:8123",
        help="ClickHouse HTTP endpoint URL (default: http://localhost:8123)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Custom output file path for features.json",
    )
    args = parser.parse_args()

    simulate = args.simulate_duplication and not args.clean
    out = Path(args.output) if args.output else None

    features = extract_and_emit(
        simulate_duplication=simulate,
        output_path=out,
        live_db=args.live_clickhouse,
        clickhouse_url=args.clickhouse_url,
    )
    mode_str = "DUPLICATED (280 features, 80 shadow)" if simulate else "CLEAN (200 features)"
    sys.stderr.write(f"[dirichlet-extractor] Emitted {len(features)} features [{mode_str}]\n")


if __name__ == "__main__":
    main()
