-- ============================================================================
-- Migration: 001_bot_signals.sql
-- Service: Dirichlet Edge Security Analytics & Bot Mitigation
-- Description: Canonical schema declaring all 200 production telemetry signals
--              spanning 6 core edge security domains.
-- ============================================================================

CREATE DATABASE IF NOT EXISTS bot_signals;

CREATE TABLE IF NOT EXISTS bot_signals.events
(
    -- Primary Event Metadata
    event_id                                UUID DEFAULT generateUUIDv4(),
    timestamp                               DateTime64(3, 'UTC') DEFAULT now64(3),
    zone_id                                 LowCardinality(String),
    request_id                              FixedString(32),

    -- Domain 1: TLS & Cryptographic Layer (35 features)
    tls_ja4_digest                          FixedString(36),
    tls_ja3_hash                            FixedString(32),
    tls_version                             LowCardinality(String),
    tls_cipher_suite                        LowCardinality(String),
    tls_extension_count                     UInt16,
    tls_extension_order_hash                UInt64,
    tls_elliptic_curves                     Array(UInt16),
    tls_ec_point_formats                    Array(UInt8),
    tls_signature_algorithms                Array(UInt16),
    tls_alpn_negotiated                     LowCardinality(String),
    tls_alpn_advertised_count               UInt8,
    tls_session_resumption_type             LowCardinality(String),
    tls_session_ticket_length               UInt16,
    tls_early_data_accepted                 UInt8,
    tls_sni_matches_host                    UInt8,
    tls_sni_entropy                         Float32,
    tls_client_random_entropy               Float32,
    tls_cert_compression_algo               LowCardinality(String),
    tls_key_share_group                     UInt16,
    tls_psk_key_exchange_modes              UInt8,
    tls_supported_versions_count            UInt8,
    tls_grease_present                      UInt8,
    tls_grease_cipher_id                    UInt16,
    tls_grease_group_id                     UInt16,
    tls_renegotiation_info_present          UInt8,
    tls_extended_master_secret              UInt8,
    tls_record_size_limit                   UInt32,
    tls_certificate_status_req              UInt8,
    tls_heartbeat_enabled                   UInt8,
    tls_signed_cert_timestamp               UInt8,
    tls_post_handshake_auth                 UInt8,
    tls_delegated_credentials               UInt8,
    tls_handshake_latency_us                UInt32,
    tls_connection_reuse_depth              UInt16,
    tls_ocsp_stapling_requested             UInt8,

    -- Domain 2: TCP & Transport Layer (30 features)
    tcp_syn_ack_rtt_us                      UInt32,
    tcp_initial_window_size                 UInt16,
    tcp_window_scaling_factor               UInt8,
    tcp_mss_declared                        UInt16,
    tcp_mss_mtu_alignment                   UInt8,
    tcp_ttl_observed                        UInt8,
    tcp_ttl_hop_variance                    UInt8,
    tcp_selective_ack_permitted             UInt8,
    tcp_sack_blocks_count                   UInt8,
    tcp_timestamp_enabled                   UInt8,
    tcp_timestamp_echo_rtt_us               UInt32,
    tcp_ecn_echo_flag                       UInt8,
    tcp_congestion_notification             UInt8,
    tcp_fast_open_cookie_present            UInt8,
    tcp_retransmission_count                UInt16,
    tcp_duplicate_ack_ratio                 Float32,
    tcp_out_of_order_packets                UInt16,
    tcp_zero_window_probes                  UInt8,
    tcp_window_update_frequency             Float32,
    tcp_urg_pointer_zero                    UInt8,
    tcp_rst_flag_seen                       UInt8,
    tcp_fin_latency_ms                      UInt32,
    tcp_paws_rejection_count                UInt8,
    tcp_flow_control_choke_events           UInt8,
    tcp_nagle_algorithm_active              UInt8,
    tcp_smoothed_rtt_us                     UInt32,
    tcp_rtt_variance_us                     UInt32,
    tcp_min_rtt_us                          UInt32,
    tcp_buffer_bloat_factor                 Float32,
    tcp_transport_anomaly_flags             UInt32,

    -- Domain 3: HTTP/2 & HTTP/3 Frame Protocol (35 features)
    http_protocol_version                   LowCardinality(String),
    h2_settings_header_table_size           UInt32,
    h2_settings_enable_push                 UInt8,
    h2_settings_max_concurrent_streams      UInt32,
    h2_settings_initial_window_size         UInt32,
    h2_settings_max_frame_size              UInt32,
    h2_settings_max_header_list_size        UInt32,
    h2_settings_order_hash                  UInt64,
    h2_settings_pseudo_header_order_hash    UInt64,
    h2_window_update_interval_ms            Float32,
    h2_window_update_increment              UInt32,
    h2_stream_priority_weight               UInt16,
    h2_stream_exclusive_flag                UInt8,
    h2_stream_dependency_id                 UInt32,
    h2_rst_stream_error_code                UInt32,
    h2_rst_stream_count                     UInt16,
    h2_ping_rtt_us                          UInt32,
    h2_ping_payload_randomness              Float32,
    h2_data_frame_fragmentation_ratio       Float32,
    h2_continuation_frame_count             UInt8,
    h2_hpack_compression_ratio             Float32,
    h2_hpack_dynamic_table_entries          UInt16,
    h2_multiplexed_streams_active           UInt16,
    h2_idle_stream_eviction_count           UInt16,
    h3_max_idle_timeout_ms                  UInt32,
    h3_max_field_section_size               UInt32,
    h3_qpack_max_table_capacity             UInt32,
    h3_qpack_blocked_streams                UInt16,
    h3_ack_delay_exponent                   UInt8,
    h3_active_connection_id_limit           UInt8,
    h3_quic_packet_number_variance          Float32,
    h3_datagram_frame_accepted              UInt8,
    h3_grease_frame_seen                    UInt8,
    h3_stream_reset_ratio                   Float32,
    h2_frame_anomaly_score                  Float32,

    -- Domain 4: Header & Request Entropy (35 features)
    header_count                            UInt16,
    header_order_hash                       UInt64,
    header_case_permutation_hash            UInt64,
    header_name_entropy                     Float32,
    header_value_entropy                    Float32,
    header_user_agent_hash                  UInt64,
    header_user_agent_entropy               Float32,
    header_accept_encoding_hash             UInt64,
    header_accept_language_order_hash       UInt64,
    header_accept_language_qvalue_variance  Float32,
    header_accept_mime_order_hash           UInt64,
    header_authorization_type               LowCardinality(String),
    header_cookie_count                     UInt16,
    header_cookie_name_order_hash           UInt64,
    header_cookie_entropy                   Float32,
    header_sec_ch_ua_hash                   UInt64,
    header_sec_fetch_dest                   LowCardinality(String),
    header_sec_fetch_mode                   LowCardinality(String),
    header_sec_fetch_site                   LowCardinality(String),
    header_sec_fetch_user                   UInt8,
    header_referrer_entropy                 Float32,
    header_origin_matches_host              UInt8,
    header_cors_preflight_present           UInt8,
    header_x_forwarded_for_count            UInt8,
    header_range_request_declared           UInt8,
    header_te_trailers_declared             UInt8,
    header_upgrade_insecure_requests        UInt8,
    header_dnt_signal                       UInt8,
    header_unknown_custom_count             UInt8,
    header_pseudo_path_entropy              Float32,
    header_query_param_entropy              Float32,
    header_query_param_count                UInt16,
    header_body_content_length              UInt64,
    header_content_type_hash                UInt64,
    header_entropy_heuristic_score          Float32,

    -- Domain 5: IP & BGP Network Reputation (35 features)
    net_asn                                 UInt32,
    net_as_organization_tier                UInt8,
    net_bgp_prefix_length                   UInt8,
    net_bgp_route_flap_rate                 Float32,
    net_bgp_as_path_length                  UInt8,
    net_bgp_origin_stability                Float32,
    net_residential_proxy_score             Float32,
    net_datacenter_egress_probability       Float32,
    net_vpn_provider_token                  LowCardinality(String),
    net_tor_exit_node                       UInt8,
    net_i2p_relay_flag                      UInt8,
    net_cidr_subnet_anomaly_score           Float32,
    net_geo_country_code                    FixedString(2),
    net_geo_region_asn_alignment            UInt8,
    net_ip_reputation_tier                  UInt8,
    net_ip_history_abuse_reports            UInt32,
    net_reverse_dns_match_domain            UInt8,
    net_reverse_dns_entropy                 Float32,
    net_port_scan_history_score             Float32,
    net_client_subnet_slash24_density       UInt32,
    net_request_velocity_1s                 UInt32,
    net_request_velocity_10s                UInt32,
    net_request_velocity_60s                UInt32,
    net_burst_concurrency_ratio             Float32,
    net_tcp_anycast_colo_hop_count          UInt8,
    net_colo_distance_km                    Float32,
    net_egress_mtu_probe_result             UInt16,
    net_dns_resolution_rtt_us               UInt32,
    net_dns_resolver_asn_matches_client     UInt8,
    net_edns_client_subnet_present          UInt8,
    net_icmp_reachability_flags             UInt8,
    net_hop_latency_jitter_us               UInt32,
    net_bogons_filter_passed                UInt8,
    net_autonomous_system_cone_size         UInt32,
    net_ip_threat_vector_score              Float32,

    -- Domain 6: Client Hints & Behavioral Signals (30 features)
    client_device_memory_gb                 UInt8,
    client_hardware_concurrency             UInt8,
    client_screen_pixel_ratio               Float32,
    client_screen_aspect_ratio              Float32,
    client_screen_color_depth               UInt8,
    client_touch_event_support              UInt8,
    client_touch_points_max                 UInt8,
    client_canvas_winding_hash              UInt64,
    client_webgl_vendor_hash                UInt64,
    client_webgl_renderer_hash              UInt64,
    client_audio_latency_variance           Float32,
    client_audio_oscillator_hash            UInt64,
    client_speech_voices_count              UInt16,
    client_plugins_length                   UInt16,
    client_battery_charging_flag            UInt8,
    client_battery_level                    Float32,
    client_connection_effective_type        LowCardinality(String),
    client_connection_downlink_mbps         Float32,
    client_connection_rtt_ms                UInt32,
    client_save_data_header                 UInt8,
    client_math_precision_hash              UInt64,
    client_error_stack_trace_entropy        Float32,
    client_navigator_webdriver_flag         UInt8,
    client_headless_chrome_score            Float32,
    client_automation_prototype_tampered    UInt8,
    client_js_execution_quantum_jitter_us   UInt32,
    client_event_loop_latency_ms            Float32,
    client_mouse_trajectory_curvature       Float32,
    client_keystroke_interarrival_variance  Float32,
    client_behavioral_ml_anomaly_score      Float32
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (zone_id, toDate(timestamp), net_asn, event_id);
